#baseURL               = "https://127.0.0.1:1313"
languageCode          = "zh-CN"
title                 = "æ±Ÿå°ç™½ä¸ªäººå¯¼èˆª"
theme                 = "WebStack"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true


[params]
    author        = "ğŸ˜¶â€ğŸŒ«ï¸"
    description   = "Webstack-Hugo ç½‘å€å¯¼èˆª | Hugo ä¸»é¢˜ BY Bio IT çˆ±å¥½è€…"
    siteurl       = "./"
    upload        = "/link"  # å·¦ä¾§å¯¼èˆªæ çš„"ç½‘ç«™æäº¤"
    about         = ""   # å·¦ä¾§å¯¼èˆªæ çš„"å…³äºå¯¼èˆª"é¡µé¢(./about)
    repository    = ""  
    enablePreLoad = true		    		           # ç½‘ç«™å®Œå…¨æ‰“å¼€å‰é¢„åŠ è½½åŠ¨ç”»
    textPreLoad   = "æ±Ÿå°ç™½ä¸ªäººå¯¼èˆª" 		           # é¢„åŠ è½½çš„åŠ¨ç”»æ–‡å­—, åªæœ‰å½“enablePreLoad=trueæ—¶ç”Ÿæ•ˆ
    expandSidebar = true                                          # é»˜è®¤å±•å¼€å·¦ä¾§è¾¹å¯¼èˆªæ 
    logosPath     = "assets/images/logos"			   # ç½‘ç«™æ¯ä¸ªå¯¼èˆªåœ°å€logoå­˜æ”¾åœ°å€
    defaultLogo   = "https://www.uusb.cf/img/favicon.png"             # logoå›¾ç‰‡èµ„æºä¸å­˜åœ¨æˆ–è€…é”™è¯¯æ—¶, é»˜è®¤æ˜¾ç¤ºçš„logo; è¯¥å‚æ•°å¦‚ä¸ºç©º,å°†ä¼šä¸€ç›´åŠ è½½å¯¹åº”çš„logo,ç›´è‡³æˆåŠŸ

[params.seo]    
    baiduhmid     = 'efccc04cb44fc49faddac5876180b369'             # ç™¾åº¦ç»Ÿè®¡ hm.src çš„ ID
    baiduSiteVer  = 'codeva-cCAOSG8MBO'                            # ç™¾åº¦HTMLæ ‡ç­¾éªŒè¯(baidu-site-verification)

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7" # Qå¤©æ°”

[params.images]
    favicon           = "https://www.uusb.cf/img/favicon.png"
    searchImageL      = "assets/images/bg-dna.jpg"		#æœç´¢éƒ¨åˆ†æµ…è‰²èƒŒæ™¯å›¾assets/images/bg-dna.jpg
    searchImageD      = "assets/images/bg-dna.jpg"		#æœç´¢éƒ¨åˆ†æ·±è‰²èƒŒæ™¯å›¾assets/images/bg-dna.jpg
    logoExpandLight   = "assets/images/bt8-expand-light.png"
    logoExpandDark    = "assets/images/bt8-expand-dark.png"
    logoCollapseLight = "assets/images/bt.png"
    logoCollapseDark  = "assets/images/bt.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = 'Â© 2022 - 2023 BY <br />ğŸ’•<span id="span_dt_dt"></span>ğŸ’•'
